version: '3'
services:
  postgres:
        image: 'postgres:latest'
        environment:
          - POSTGRES_PASSWORD=12345asdf
          - POSTGRES_USER=postgres
          - POSTGRES_DB=simple_blog_api
  api:
    depends_on:
      - postgres
    build:
        context: .
        dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345asdf
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

